In [1]:
# welcome to numpy tutorial

In [39]:
import numpy as np

In [3]:
arr = np.array([[3,6,32,7]], np.int8)

In [4]:
arr.dtype

dtype('int8')

# Array creation

In [5]:
lst = np.array([[1,2,3],[4,5,6]])

In [6]:
lst

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
lst.shape

(2, 3)

In [8]:
z = np.zeros((2,110))

In [9]:
z.shape


(2, 110)

In [10]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
lnspace = np.linspace(1,5,50)
lnspace

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [12]:
emp = np.empty((2,5))
emp

array([[4.67296746e-307, 1.69121096e-306, 3.22647253e-307,
        2.67018777e-306, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.42419530e-306, 1.42419530e-306]])

In [13]:
emplike = np.empty_like(lst)
emplike

array([[1915693390,        134, 1970144730],
       [1920561261,         58, 1970146394]])

In [14]:
inden = np.identity(10)
inden

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
inden.shape


(10, 10)

In [16]:
arr1 = np.arange(56)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [17]:
arr1.reshape(len(arr1)
             ,1)
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [18]:
arr =[[1,2,3],[4,5,6],[7,1,0]]
arr

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [19]:
arr = np.array(arr)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [20]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [21]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [22]:
arr.flat

In [23]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [24]:
arr.ndim

2

In [25]:
arr.nbytes


36

In [26]:
#arr = np.array([1,22,3,4])

In [27]:
arr.argmax()

6

In [28]:
arr.argmin()

8

In [29]:
arr.argsort()


array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [32]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [33]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [34]:
arr2 = np.array(([5,1,2],[51,6,7],[8,1,2]))
arr+arr2

array([[ 6,  3,  5],
       [55, 11, 13],
       [15,  2,  2]])

In [37]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [41]:
arr.sum()

29

In [42]:
arr.min()

0

In [43]:
arr.max()

7

In [44]:
arr.where(5)

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [45]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [46]:
np.where(arr>2)


(array([0, 1, 1, 1, 2], dtype=int64), array([2, 0, 1, 2, 0], dtype=int64))